#### Conv-TasNet Setting
name: Conv_Tasnet
gpu_ids: [0]

#### Dataset Configure
datasets:
  num_workers: 2
  batch_size: 4
  fs: 8000
  chunk_len: 3
  chunk_size: 24000

  train:
    mix_scp: ./scp/tr_mix.scp
    ref_scp:
      - ./scp/tr_s1.scp
      - ./scp/tr_s2.scp
    sr: 8000

  val:
    mix_scp: ./scp/cv_mix.scp
    ref_scp:
      - ./scp/cv_s1.scp
      - ./scp/cv_s2.scp
    sr: 8000

#### Training settings
train:
  lr: !!float 3e-4
  log_interval: 100
  min_lr: 1e-6
  patience: 2
  factor: 0.5
  clip_norm: 5.0
  num_epochs: 100
  checkpoint: /content/drive/MyDrive/ConvTasNet/checkpoints

#### Network configure
net_conf:
  n_fft: 256
  hop_length: 64
  B: 96
  H: 256
  P: 3
  X: 7
  R: 3
  num_spks: 2
  norm: gln
  causal: false

#### Resume model
resume:
  # path: /content/drive/MyDrive/ConvTasNet/checkpoints/last.pt
  resume_state: false
