#### Conv-TasNet Setting
name: Conv_Tasnet
gpu_ids: [0]
epochs: 100

#### Dataset Configure
datasets:
  num_workers: 2
  batch_size: 4
  fs: 8000
  chunk_len: 3
  chunk_size: 24000

  train:
    mix_scp: ./scp/tr_mix.scp
    ref_scp:
      - ./scp/tr_s1.scp
      - ./scp/tr_s2.scp
    sr: 8000

  val:
    mix_scp: ./scp/cv_mix.scp
    ref_scp:
      - ./scp/cv_s1.scp
      - ./scp/cv_s2.scp
    sr: 8000

#### Training settings
train:
  lr: !!float 5e-4
  log_interval: 100

  min_lr: 1e-8
  patience: 2
  factor: 0.5
  logging_period: 50
  clip_norm: 200
  num_epochs: 100
  checkpoint: /content/drive/MyDrive/ConvTasNet/checkpoints

#### Optimizer kwargs (NO lr here)
optimizer_kwargs:
  weight_decay: 1e-5

#### Network configure (OPTIMIZED)
net_conf:
  n_fft: 256
  hop_length: 64

  B: 96
  H: 256
  P: 3
  X: 7
  R: 3

  num_spks: 2
  norm: gln
  causal: false

#### Resume model
resume:
  path: /content/drive/MyDrive/ConvTasNet/checkpoints/last.pt
  resume_state: true
