#### Conv-TasNet Setting
name: Conv_Tasnet
gpu_ids: [0]          # Single GPU (GPU 0)
epochs: 100

#### Dataset Configure
datasets:
  num_workers: 2      # Safe for single GPU
  batch_size: 4
  fs: 8000
  chunk_len: 3
  chunk_size: 24000   # 3 sec × 8kHz

  train:
    mix_scp: ./scp/tr_mix.scp
    ref_scp:
      - ./scp/tr_s1.scp
      - ./scp/tr_s2.scp
    sr: 8000

  val:
    mix_scp: ./scp/cv_mix.scp
    ref_scp:
      - ./scp/cv_s1.scp
      - ./scp/cv_s2.scp
    sr: 8000

#### Training settings
train:
  optimizer: adam
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5
  logging_period: 50
  clip_norm: 200
  num_epochs: 100
  checkpoint: Conv-TasNet-new

optimizer_kwargs:
  lr: !!float 1e-3
  weight_decay: !!float 1e-5

#### Network configure (OPTIMIZED)
net_conf:
  n_fft: 256
  hop_length: 64

  B: 64        # bottleneck channels (↓ memory + faster)
  H: 176       # TCN hidden channels (↓ from 512)
  P: 3
  X: 5         # blocks per repeat (↓ from 8)
  R: 2         # repeats (↓ from 3)

  num_spks: 2
  norm: gln
  causal: false

#### Resume model
resume:
  path: ./Conv-TasNet-new
  resume_state: false
